# Generated by Django 3.2.8 on 2021-10-14 06:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('growerlabs', '0002_auto_20211008_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contributions',
            field=models.ManyToManyField(related_name='contributions', to='growerlabs.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(related_name='contributors', to=settings.AUTH_USER_MODEL),
        ),
    ]
