# Generated by Django 3.2.8 on 2021-10-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growerlabs', '0003_auto_20211014_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contributions',
        ),
        migrations.AlterField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(related_name='contributors', to='growerlabs.Profile'),
        ),
    ]
